project:
  type: website
  output-dir: docs
  
execute:
  cache: true
  freeze: auto

website:
  title: "FIP 606"
  navbar:
    left:
      - text: Básico do R
        menu: 
          - href: index.qmd
            text: Início
          - href: aula1.qmd
            text: Quarto document
          - href: aula2.qmd
            text: Carregar pacotes
          - href: aula3.qmd
            text: Dataframe
      - text: Gráficos em R
        menu:
          - href: aula4.qmd
            text: GGPLOT
          - href: aula5.qmd
            text: Boxplot
          - href: aula6.qmd
            text: Scarterplot
          - href: aula7.qmd
            text: Transformando os dados
      - text: Teste T
        menu:
          - href: aula8.qmd
            text: Teste de hipótese
          - href: aula9.qmd
            text: Amostras dependentes
            
      - text: ANOVA
        menu:
          - href: aula10.qmd
            text: Anova 1 ou mais fatores
          - href: aula11.qmd
            text: Anova fatorial
          - href: aula12.qmd
            text: Anova em bloco (DBC)
      - text: Regr. e Correlação
        menu: 
          - href: aula13.qmd
            text: Regressão linear
          - href: aula17.qmd
            text: Regressão não-linear 
          - href: aula14.qmd
            text: Análise de correlação
      - text: Tab. de contigência
        menu: 
          - href: aula15.qmd
            text: T. de contigência
      - text: MAPA
        menu: 
          - href: aula16.qmd
            text: Mapas 
      - text: Box_Cox
        menu: 
          - href: aula18.qmd
            text: Tranformação de dados em box-cox      
          
    right:
      - icon: github
        href: https://github.com/Arlamsilva
      - icon: linkedin
        href: https://linkedin.com/in/arlam-fernandes-596603162
      - icon: twitter
        href: https://twitter.com/arlam_da?t=2_JZ3BPWr192iJy9MZbVOw&s=08
     
format:
  html:
    theme: Navbars
    css: styles.css
    toc: true

editor: visual

