---
title: "aula14"
format: html
---

```{r}
library(readxl)
library(tidyverse)
estande <- read_excel("dados-diversos.xlsx", "estande")

estande |> 
  ggplot(aes(trat, nplants, group = exp))+
  geom_point()+
  facet_wrap(~exp)+
  ylim(0,max(estande$nplants))+
  geom_smooth(se = F)

```
```{r}
library(ggtext)
estande2 <- estande |>
  filter(exp == 2)|>
  group_by(trat) |> 
  summarise(mean_nplants = mean(nplants))

estande2 |> 
  ggplot(aes(trat, mean_nplants))+
  geom_point()+
  #geom_line()+
  geom_smooth(se = F, formula = y ~ poly(x, 2), method = "lm", color = "black")+
  theme_minimal()+
  annotate(geom = "text",
           x = 25, y = 70,
           label = "y = 66.3 - 1.777x + 0.0222x2 
R2 = 0.88")
```

```{r}
estande2 <- estande2 |> 
  mutate(trat2 = trat^2)

m1 <- lm(mean_nplants ~ trat, 
         data = estande2)
summary(m1)
hist(m1$residuals)

m2 <- lm(mean_nplants ~ trat + trat2, 
         data = estande2)
summary(m2)
AIC(m1, m2)

```
# Duas variáveis resposta

```{r}
mofo <- read_excel("dados-diversos.xlsx",
                   "mofo")
mofo |> 
  ggplot(aes(inc, yld))+
  geom_point()+
  geom_smooth(se = F, method = "lm")+
  facet_wrap(~ study)
```






